export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const UPDATE_ITEM_BASKET_REQUEST = 'UPDATE_ITEM_BASKET_REQUEST';
export const GET_SCANNED_ITEMS_REQUEST = 'GET_SCANNED_ITEMS_REQUEST';

export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const UPDATE_ITEM_BASKET_SUCCESS = 'UPDATE_ITEM_BASKET_SUCCESS';
export const GET_SCANNED_ITEMS_SUCCESS = 'GET_SCANNED_ITEMS_SUCCESS';
export const ADD_NEW_ITEM_BASKET_SUCCESS = 'ADD_NEW_ITEM_BASKET_SUCCESS';

