const ActionTypes = {
  GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
  UPDATE_ITEM_BASKET_REQUEST: 'UPDATE_ITEM_BASKET_REQUEST',
  GET_SCANNED_ITEMS_REQUEST: 'GET_SCANNED_ITEMS_REQUEST',
  GET_PROMOTIONS_REQUEST: 'GET_PROMOTIONS_REQUEST',
  GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  UPDATE_ITEM_BASKET_SUCCESS: 'UPDATE_ITEM_BASKET_SUCCESS',
  GET_SCANNED_ITEMS_SUCCESS: 'GET_SCANNED_ITEMS_SUCCESS',
  ADD_NEW_ITEM_BASKET_SUCCESS: 'ADD_NEW_ITEM_BASKET_SUCCESS',
  GET_PROMOTIONS_SUCCESS: 'GET_PROMOTIONS_SUCCESS',
};
Object.freeze(ActionTypes);
export default ActionTypes;
