export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const ADD_ITEM_BASKET_REQUEST = 'ADD_ITEM_BASKET_REQUEST';
export const UPDATE_ITEM_BASKET_REQUEST = 'UPDATE_ITEM_BASKET_REQUEST';
export const REMOVE_ITEM_BASKET_REQUEST = 'REMOVE_ITEM_BASKET_REQUEST';

export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const ADD_ITEM_BASKET_SUCCESS = 'ADD_ITEM_BASKET_SUCCESS';
export const UPDATE_ITEM_BASKET_SUCCESS = 'UPDATE_ITEM_BASKET_SUCCESS';
export const REMOVE_ITEM_BASKET_SUCCESS = 'REMOVE_ITEM_BASKET_SUCCESS';

