const PromotionTypes = {SINGLE_PRODUCT_SALE:"SINGLE_PRODUCT_SALE", GROUP_PROMOTIONAL_PRICE:"GROUP_PROMOTIONAL_PRICE", ADDITIONAL_PRODUCT_DISCOUNT:"ADDITIONAL_PRODUCT_DISCOUNT"}
Object.freeze(PromotionTypes)
export default PromotionTypes;